language: python
python:
  - "3.6"
before_install:
  - export DJANGO_SETTINGS_MODULE=online_quiz_portal.settings
install:
  - pip3 install pipenv
  - pipenv install
script:
  - cd src
  - source "$(pipenv --venv)"/bin/activate
  - flake8 .
  - python3 manage.py makemigrations
  - python3 manage.py migrate
